# Limit Codecov reports to the SplitFairly namespace
coverage:
  status:
    project:
      default:
        target: 0
  precision: 2
  round: down
reports:
  - name: SplitFairly
    paths:
      - backend/src/SplitFairly
    # Only show this report on the Codecov UI
    # see https://docs.codecov.com/docs/codecov-yaml#section-reports
