apiVersion: v2
name: split-fairly
description: Helm chart for the split-fairly application
type: application
version: 0.1.5
appVersion: "0.1.5"
keywords:
  - split-fairly
  - web
  - php
  - mysql
maintainers:
  - name: Martin Komischke
    email: "martin@example.com"

